spring.application.name=payment_service
server.port=8081

# DATABASE CONFIG
spring.datasource.url=${PAYMENT_DB_URL:jdbc:postgresql://localhost:5432/payment_service}
spring.datasource.username=${PAYMENT_DB_USERNAME:postgres}
spring.datasource.password=${PAYMENT_DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SECURITY CONFIG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
fraud.service.url=${FRAUD_SERVICE_URL:http://localhost:8080}

# KAFKA CONFIG
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=default-group
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
